## CHANGE this to the name of your plugin.
name: MagicXpansion

## CHANGE this to your username.
author: Hexagone

## CHANGE this to a meaningful but short description of your plugin.
description: A Slimefun4 addon that adds more magical items and more talismans.

## CHANGE this to the path of the class that extends JavaPlugin.
main: me.hexagone.magicxpansion.MagicXpansion

## You can change this to link to your website or repository. You can also remove this line if you want to.
website: https://github.com/HexaGone68/MagicXpansion

## This value is automatically replaced by the version specified in your pom.xml file.
## Do not change this.
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: 1.14

## This is required and marks Slimefun as a plugin dependency.
depend:
- Slimefun